name = "find-home"
main = "worker.js"
compatibility_date = "2026-06-10"

[[d1_databases]]
binding = "IOT_DB"
database_name = "iot_db"
database_id = "2d5c782b-d316-4e4c-9879-3064a06f2015"

[observability]
enabled = false

[observability.logs]
enabled = true
persist = true
invocation_logs = true