name = "find-home"
main = "worker.js"
compatibility_date = "2026-06-10"

[[d1_databases]]
binding = "IOT_DB"
database_name = "mk_db"
database_id = "d1fe63d8-733b-446f-ba72-38c464f3c71b"

[observability]
enabled = false

[observability.logs]
enabled = true
persist = true
invocation_logs = true