name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: # Allows you to trigger it manually from the GitHub UI.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync upstream _worker.js into worker.js
        run: |
          git remote add upstream https://github.com/itsyebekhe/nahan.git
          git fetch upstream main
          git show upstream/main:_worker.js > worker.js
          git add worker.js
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: sync upstream _worker.js into worker.js" --allow-empty
          git push origin main